-- Generated by hypr2lua-web.
-- Source: hyprland.conf

hl.config({
  general = {
    col = {
      active_border = {
        colors = { "rgba(3A403Bee)", "rgba(05050Aee)" },
        angle = 45,
      },
      inactive_border = "rgb(05050A)",
    },
    border_size = 2,
    gaps_in = 3,
    gaps_out = 3,
  },
  group = {
    col = {
      border_active = {
        colors = { "rgba(3A403Bee)", "rgba(05050Aee)" },
        angle = 45,
      },
      border_inactive = "rgb(05050A)",
    },
    groupbar = {
      col = {
        active = "rgba(7B726A99)",
        inactive = "rgba(3A403B88)",
      },
      text_color = "rgb(BDB5AA)",
      text_color_inactive = "rgba(E24C00ff)",
    },
  },
  decoration = {
    rounding = 0,
    shadow = {
      enabled = true,
      render_power = 16,
      range = 8,
      color = "rgba(0,0,0, 0.8)",
    },
  },
})
